sudo: false
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=linters
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.7
      sudo: required
      dist: xenial
      env: TOXENV=py37
    # TODO: need to make special environment for horton (i.e. install conda and install horton)
    # - python: 3.6
    #   env: TOXENV=horton
    # TODO: need to install pyscf
    # - python: 3.6
    #   env: TOXENV=pyscf
    - python: 3.6
      env: TOXENV=keras
      before_script:
        - pip install --user keras
  fast_finish: true
  allow_failures:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.7
      sudo: required
      dist: xenial
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=keras
install: pip install tox
script: tox
